/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaAgregarCondicion.java
 *
 * Created on 1/06/2010, 04:26:05 PM
 */

package edu.unicartagena.ia.gui;

import edu.unicartagena.ia.logica.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Coordinador
 */
public class VistaAgregarCondicion extends javax.swing.JDialog {

    private List data;
    private CargadorDeCondicion loader;

    /** Creates new form VistaAgregarCondicion */
    public VistaAgregarCondicion(java.awt.Frame parent, boolean modal, CargadorDeCondicion loader) {
        super(parent, modal);
        initComponents();

        this.loader = loader;

        data = new LinkedList();
        cargarAtrib();

        startGUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atributos = new javax.swing.JComboBox();
        valores = new javax.swing.JComboBox();
        cancel = new javax.swing.JButton();
        acept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Condicion");
        setResizable(false);

        jLabel1.setText("Atributo");

        jLabel2.setText("Valor");

        cancel.setText("Cancelar");

        acept.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(acept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(valores, 0, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(atributos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(acept))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acept;
    private javax.swing.JComboBox atributos;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox valores;
    // End of variables declaration//GEN-END:variables

    private void cargarAtrib() {

        CargarAtributos ca = new CargarAtributos();

        String[] atrib = ca.getAtributos();

        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(atrib);
        atributos.setModel(dcbm);

        for (int i = 0; i < atrib.length; i++) {
            String val[] = ca.getValores( atrib[i] );
            data.add( val );
        }

        dcbm = new DefaultComboBoxModel( (String[])data.get(0) );

        valores.setModel(dcbm);
    }

    private void startGUI() {

        atributos.addActionListener( new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                System.out.println("acccc");
                int selecc = atributos.getSelectedIndex();
                String vv[] = (String[]) data.get(selecc);

                DefaultComboBoxModel dcbm = new DefaultComboBoxModel(vv);
                valores.setModel(dcbm);
            }
        } );

        acept.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                String atrib = atributos.getSelectedItem().toString();
                String valor = valores.getSelectedItem().toString();

                VistaAgregarCondicion.this.setVisible(false);
                
                loader.cargar( new Condicion(atrib, valor) );
            }
        });

        cancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                VistaAgregarCondicion.this.setVisible(false);
            }
        });

    }
}
